/* Exact copy extracted from the seven boards. Screen IDs match design/screens.json. */
export const COPY = {
  brand: 'again.',
  s01: {
    signIn: 'Sign in',
    heading: 'Give your photo\na pulse.',
    sampleLabel: 'TRY A MOMENT',
    cta: 'Choose a photo',
    sub: 'One photo. Ten seconds of life.',
    howItWorks: 'How it works',
    pricing: 'Pricing',
  },
  s02: {
    heading: 'Keep your moment.',
    sub: 'Sign in to create and save your films.',
    apple: 'Continue with Apple',
    google: 'Continue with Google',
    or: 'or',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    cta: 'Email me a code',
    newHere: 'New here? Your account is created automatically.',
    legalPrefix: 'By continuing, you agree to our ',
    terms: 'Terms',
    and: ' and ',
    privacy: 'Privacy Policy',
  },
  s03: {
    heading: 'Check your inbox.',
    subPrefix: 'Enter the 6-digit code sent to ',
    cta: 'Continue',
    resend: 'Resend code',
    changeEmail: 'Change email',
    waiting: 'Your photo is waiting for you.',
  },
  s04: {
    skip: 'Skip',
    heading: 'A little life.\nIn three steps.',
    steps: [
      { n: '01', title: 'Choose a photo', body: 'Pick a photo from your camera roll.' },
      { n: '02', title: 'Pick the feeling', body: 'Set the mood or add your own direction.' },
      { n: '03', title: 'Save your film', body: 'We’ll animate your photo into a 10-second video.' },
    ],
    note: '1 credit creates one 10-second film.',
    cta: 'Let’s make a film',
    privacy: 'Your photos stay private.',
  },
  s05: {
    heading: 'What comes\nto life next?',
    cta: 'Choose a photo',
    formats: 'JPG, PNG or HEIC · Up to 20 MB',
    inspiration: 'Need a little inspiration?',
  },
  s06: {
    yourPhoto: 'YOUR PHOTO',
    tenSec: '10 SEC',
    changePhoto: 'Change photo',
    heading: 'Make it move.',
    addDirection: 'Add your own direction',
    cta: 'Animate photo',
    note: 'Uses 1 credit · 10-second video',
  },
  s07: {
    heading: 'A moment\nin the making.',
    steps: ['Photo\nreceived', 'Creating\nmovement', 'Finishing\nyour film'],
    mayTake: 'This may take a few minutes.',
    leave: 'You can leave this page.\nYour film will appear in My films.',
    cta: 'Go to My films',
  },
  s08: {
    saved: 'Saved to ',
    savedLink: 'My films',
    heading: 'Now it’s\na moment.',
    pressToSee: 'Press to see photo',
    save: 'Save film',
    share: 'Share',
    another: 'Animate another',
  },
  s09: {
    heading: 'My films.',
    sub: 'Your moments, moving.',
    tabs: ['All', 'Ready', 'Creating'],
    creating: 'Creating',
    inProgress: 'In progress',
    today: 'Today',
  },
  s10: {
    heading: 'More moments.\nYour pace.',
    tabs: ['Credit packs', 'Monthly'],
    note: '1 credit = one 10-second video.',
    popular: 'POPULAR',
    footer: 'One-time payment. Credits never expire.',
    cta: (n: number) => `Continue with ${n} credit${n === 1 ? '' : 's'}`,
    already: 'Already have credits? ',
    refresh: 'Refresh balance',
  },
  s11: {
    heading: 'Keep creating.',
    sub: 'A fresh set of credits every month.',
    perMonth: '/ month',
    monthlySub: (n: number) => `${n} credits each month`,
    notes: ['1 credit = one 10-second video.', 'Monthly credits reset at renewal.', 'Purchased credits stay in your balance.', 'Cancel anytime.'],
    cta: (name: string, price: string) => `Choose ${name} — ${price}/mo`,
    renews: 'Renews monthly until canceled.',
  },
  s12: {
    heading: 'Make it yours.',
    photoSaved: 'Your photo is saved',
    photoSavedSub: 'You’ll return to your draft after purchase.',
    oneTime: 'One-time purchase',
    monthly: 'Monthly subscription',
    applePay: 'Pay with Apple Pay',
    orCard: 'or pay by card',
    cardNumber: 'Card number',
    expiry: 'Expiration date',
    cvc: 'Security code',
    country: 'Billing country',
    total: 'Total today',
    tax: 'Tax calculated if applicable.',
    pay: (amount: string) => `Pay ${amount}`,
    secure: 'Secure checkout',
    terms: 'Terms',
    privacy: 'Privacy',
  },
  s13: {
    heading: 'You’re ready\nto roll.',
    added: 'credits added',
    oneTime: (price: string) => `One-time purchase · ${price}`,
    monthly: (price: string) => `Monthly plan · ${price}/mo`,
    ready: 'Your photo is ready when you are.',
    cta: 'Back to my photo',
    ctaNoDraft: 'Go to Create',
    receipt: 'View receipt',
    noSub: 'No subscription. No expiry.',
    confirming: 'Confirming payment',
  },
  s14: {
    heading: 'Your account.',
    edit: 'Edit',
    available: 'credits\navailable',
    oneCredit: 'One credit = one 10-second film',
    cta: 'Get more credits',
    rows: ['Plans & billing', 'Credit history', 'Privacy & data', 'Help & support'],
    signOut: 'Sign out',
  },
  s15: {
    heading: 'Your plan.',
    perMonth: '/ month',
    each: (n: number) => `${n} credits each month`,
    nextPayment: 'Next payment',
    monthlyLeft: 'Monthly credits left',
    purchased: 'Purchased credits',
    noExpiry: 'no expiry',
    resets: (d: string) => `Monthly credits reset on ${d}.`,
    change: 'Change plan',
    paymentMethod: 'Payment method',
    billingHistory: 'Billing history',
    cancel: 'Cancel subscription',
    cancelNote: (d: string) => `If canceled, your plan stays active until ${d}.`,
  },
  s16: {
    heading: 'Your first film\nstarts with a photo.',
    sub: 'Bring a moment to life. Keep it here.',
    cta: 'Choose a photo',
    example: 'Watch an example',
  },
  s17: {
    heading: 'Let’s try\nanother photo.',
    cta: 'Choose another photo',
    back: 'Back to Create',
    noCredits: 'No credits used.',
  },
  s18: {
    heading: 'This one\ndidn’t finish.',
    sub: 'We couldn’t complete your video.',
    returned: 'Your credit has been returned.',
    returning: 'Returning your credit…',
    retry: 'Try again · 1 credit',
    another: 'Choose another photo',
    trouble: 'Still having trouble? ',
    help: 'Get help',
  },
  s19: {
    seconds: (n: number) => `${n} seconds`,
    play: 'Play film',
    rename: 'Rename',
    download: 'Download',
    share: 'Share',
    delete: 'Delete film',
  },
  s20: {
    heading: 'Pass the\nmoment on.',
    cta: 'Share video',
    sub: 'Choose where to send it on your device.',
    download: 'Download instead',
    only: 'Only this video is shared.',
  },
  s21: {
    heading: 'Delete this film?',
    body: (title: string) => `“${title}” will be removed from My films.\nThis can’t be undone.`,
    note: 'Previously downloaded copies are not affected.',
    keep: 'Keep film',
    delete: 'Delete film',
  },
  nav: { create: 'Create', films: 'My films', account: 'Account' },
  credits: (n: number) => `${n} credit${n === 1 ? '' : 's'}`,
  demoBanner: 'Demo mode — no payments or real generation',
} as const;
